#!/bin/bash
set -euxo pipefail

curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.0/kind-linux-amd64
chmod +x ./kind
export CLUSTER_ID=bk-${BUILDKITE_STEP_ID:24}
export KUBECONFIG=$(pwd)/${CLUSTER_ID}
./kind create cluster --name ${CLUSTER_ID} --wait 5m